version: '3'
services:
  
  rails_docker_demo:
    image: coolrequest/rails_docker_demo
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: rails_docker_demo
      POSTGRES_PASSWORD: my_pg_pass123
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  