services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: coolrequest
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - rede